name: tech_travel
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2

dev_dependencies:
  flutter_native_splash:
  flutter_lints: ^4.0.0
  test:
  mockito: ^5.4.4
  build_runner: any
  mobx_codegen: any
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/langs/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/epilogue/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/epilogue/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/epilogue/Epilogue-Bold.ttf
          weight: 700
    - family: FieldWork
      fonts:
        - asset: assets/fonts/fieldwork/fieldwork_bold.otf
          weight: 700
        - asset: assets/fonts/fieldwork/fieldwork_regular.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500

flutter_native_splash:
  color: "#131418" 
  image: assets/images/logo.png 
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#131418"
